// <auto-generated />
using System;
using CrossFinaceApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrossFinaceApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrossFinaceApp.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorrespondenceFlatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrespondencePostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrespondencePostOfficeCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrespondenceStreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrespondenceStreetnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostOfficeCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("CrossFinaceApp.Models.Agreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FinancialStateId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinancialStateId");

                    b.HasIndex("PersonId");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("CrossFinaceApp.Models.FinancialState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CourtFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Interests")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutstandingLiabilites")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PenaltyInterests")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RepresentationCourtFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RepresentationVindicationCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VindicationCosts")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FinancialStates");
                });

            modelBuilder.Entity("CrossFinaceApp.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("CrossFinaceApp.Models.Agreement", b =>
                {
                    b.HasOne("CrossFinaceApp.Models.FinancialState", "FinancialState")
                        .WithMany("Agreements")
                        .HasForeignKey("FinancialStateId");

                    b.HasOne("CrossFinaceApp.Models.Person", "Person")
                        .WithMany("Agreements")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("CrossFinaceApp.Models.Person", b =>
                {
                    b.HasOne("CrossFinaceApp.Models.Address", "Address")
                        .WithMany("People")
                        .HasForeignKey("AddressId");
                });
#pragma warning restore 612, 618
        }
    }
}
