//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/ImportService")]
    public partial class Person : object
    {
        
        private ImportService.Address[] AddressesField;
        
        private ImportService.FinancialState FinancialStateField;
        
        private ImportService.IdentityDocument[] IdentityDocumentsField;
        
        private string NameField;
        
        private string NationalIdentificationNumberField;
        
        private ImportService.Phone[] PhonesField;
        
        private string SurnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportService.Address[] Addresses
        {
            get
            {
                return this.AddressesField;
            }
            set
            {
                this.AddressesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportService.FinancialState FinancialState
        {
            get
            {
                return this.FinancialStateField;
            }
            set
            {
                this.FinancialStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportService.IdentityDocument[] IdentityDocuments
        {
            get
            {
                return this.IdentityDocumentsField;
            }
            set
            {
                this.IdentityDocumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalIdentificationNumber
        {
            get
            {
                return this.NationalIdentificationNumberField;
            }
            set
            {
                this.NationalIdentificationNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImportService.Phone[] Phones
        {
            get
            {
                return this.PhonesField;
            }
            set
            {
                this.PhonesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinancialState", Namespace="http://schemas.datacontract.org/2004/07/ImportService")]
    public partial class FinancialState : object
    {
        
        private decimal CapitalField;
        
        private decimal CourtFeesField;
        
        private decimal CourtRepresentationFeesField;
        
        private decimal EnforcementFeesField;
        
        private decimal EnforcementRepresentationFeesField;
        
        private decimal FeesField;
        
        private decimal InterestField;
        
        private decimal PenaltyInterestField;
        
        private decimal PlenipotentiryFeeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Capital
        {
            get
            {
                return this.CapitalField;
            }
            set
            {
                this.CapitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CourtFees
        {
            get
            {
                return this.CourtFeesField;
            }
            set
            {
                this.CourtFeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CourtRepresentationFees
        {
            get
            {
                return this.CourtRepresentationFeesField;
            }
            set
            {
                this.CourtRepresentationFeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EnforcementFees
        {
            get
            {
                return this.EnforcementFeesField;
            }
            set
            {
                this.EnforcementFeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EnforcementRepresentationFees
        {
            get
            {
                return this.EnforcementRepresentationFeesField;
            }
            set
            {
                this.EnforcementRepresentationFeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Fees
        {
            get
            {
                return this.FeesField;
            }
            set
            {
                this.FeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Interest
        {
            get
            {
                return this.InterestField;
            }
            set
            {
                this.InterestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PenaltyInterest
        {
            get
            {
                return this.PenaltyInterestField;
            }
            set
            {
                this.PenaltyInterestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PlenipotentiryFee
        {
            get
            {
                return this.PlenipotentiryFeeField;
            }
            set
            {
                this.PlenipotentiryFeeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/ImportService")]
    public partial class Address : object
    {
        
        private string AddressTypeField;
        
        private string CityField;
        
        private string HouseNoField;
        
        private string LocaleNoField;
        
        private string PostalCodeField;
        
        private string StreetField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddressType
        {
            get
            {
                return this.AddressTypeField;
            }
            set
            {
                this.AddressTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseNo
        {
            get
            {
                return this.HouseNoField;
            }
            set
            {
                this.HouseNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocaleNo
        {
            get
            {
                return this.LocaleNoField;
            }
            set
            {
                this.LocaleNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityDocument", Namespace="http://schemas.datacontract.org/2004/07/ImportService")]
    public partial class IdentityDocument : object
    {
        
        private System.DateTime ExpirationDateField;
        
        private string NumberField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phone", Namespace="http://schemas.datacontract.org/2004/07/ImportService")]
    public partial class Phone : object
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImportService.IImportService")]
    public interface IImportService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DoImport", ReplyAction="http://tempuri.org/IImportService/DoImportResponse")]
        System.Threading.Tasks.Task<bool> DoImportAsync(ImportService.Person personalData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IImportServiceChannel : ImportService.IImportService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ImportServiceClient : System.ServiceModel.ClientBase<ImportService.IImportService>, ImportService.IImportService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ImportServiceClient() : 
                base(ImportServiceClient.GetDefaultBinding(), ImportServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IImportService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ImportServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ImportServiceClient.GetBindingForEndpoint(endpointConfiguration), ImportServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ImportServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ImportServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ImportServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ImportServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ImportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> DoImportAsync(ImportService.Person personalData)
        {
            return base.Channel.DoImportAsync(personalData);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IImportService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IImportService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/ImportService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ImportServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IImportService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ImportServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IImportService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IImportService,
        }
    }
}
